SKELETON_WIDTH_SCALE_FACTOR = 1.5
SKELETON_HEIGHT_SCALE_FACTOR = 1.5
SKELETON_ATTACK_ANIMATION_COOLDOWN = [350, 100, 350] #Milliseconds

SKELETON_TYPE = "enemy"
SKELETON_ATTACK_TYPE = "melee"
SKELETON_MOVEMENT_SPEED = 8
SKELETON_HEALTH = 100
SKELETON_DAMAGE = 60
SKELETON_ATTACK_RADIUS = 300