SKELETON_WIDTH_SCALE_FACTOR = 1.5
SKELETON_HEIGHT_SCALE_FACTOR = 1.5
SKELETON_ATTACK_ANIMATION_COOLDOWN = [350, 100, 350]

SKELETON_TYPE = "melee"
SKELETON_ATTACK_TYPE = "enemy"
SKELETON_MOVEMENT_SPEED = 480
SKELETON_HEALTH = 100
SKELETON_DAMAGE = 200
SKELETON_ATTACK_RADIUS = 300