SLIME_HEIGHT = 38
SLIME_WIDTH = 56
SLIME_HEALTH = 1000
SLIME_SPEED = 180

#For stretching effect when the slime is idle
SLIME_STRETCH_WIDTH = 51
SLIME_STRETCH_HEIGHT = 53
SLIME_ANIMATION_SPEED = 1000

ATTACK_TYPE = "player"
ATTACK_HEIGHT = 15
ATTACK_WIDTH = 15
ATTACK_DAMAGE = 20

ATTACK_RADIUS = 400
ATTACK_COOLDOWN = 300
ATTACK_SPEED = 600