CHARACTER_HEIGHT = 38
CHARACTER_WIDTH = 56
CHARACTER_HEALTH = 1000

#For stretching effect when the slime is idle
CHARACTER_STRETCH_WIDTH = 51
CHARACTER_STRETCH_HEIGHT = 53
ANIMATION_SPEED = 1000 #Millisecond

ATTACK_TYPE = "player"
ATTACK_HEIGHT = 15
ATTACK_WIDTH = 15
ATTACK_DAMAGE = 20

ATTACK_RADIUS = 400
ATTACK_COOLDOWN = 300 #Millisecond
ATTACK_SPEED = 10 #Pixels