SLIME_HEIGHT = 38
SLIME_WIDTH = 56
SLIME_SPEED = 180

SLIME_HEALTH = 5000000
SLIME_HEALTH_BAR_WIDTH = 55
SLIME_HEALTH_BAR_HEIGHT = 10

#For stretching effect when the slime is idle
SLIME_STRETCH_WIDTH = 51
SLIME_STRETCH_HEIGHT = 53
SLIME_ANIMATION_SPEED = 1000

SLIME_MAX_STAMINA = 200
SLIME_STAMINA_DRAIN = 50
SLIME_STAMINA_REGEN = 10
SLIME_STAMINA_BAR_WIDTH = 55
SLIME_STAMINA_BAR_HEIGHT = 10

ATTACK_TYPE = "player"
ATTACK_HEIGHT = 15
ATTACK_WIDTH = 15
ATTACK_DAMAGE = 20

ATTACK_RADIUS = 400
ATTACK_COOLDOWN = 300
ATTACK_SPEED = 600