SNAKE_WIDTH_SCALE_FACTOR = 1.75
SNAKE_HEIGHT_SCALE_FACTOR = 1.75
SNAKE_ATTACK_ANIMATION_COOLDOWN = [500, 300] #Milliseconds

SNAKE_TYPE = "enemy"
SNAKE_ATTACK_TYPE = "ranged"
SNAKE_MOVEMENT_SPEED = 3
SNAKE_HEALTH = 60
SNAKE_MELEE_DAMAGE = 30
SNAKE_PROJECTILE_DAMAGE = 15
SNAKE_ATTACK_RADIUS = 10000
SNAKE_PROJECTILE_OUTER_RADIUS = 50
SNAKE_PROJECTILE_RADIUS = 500
SNAKE_PROJECTILE_ATTACK_COOLDOWN = 1000 #Milliseconds
SNAKE_PROJECTILE_SPEED = 7 

SNAKE_PROJECTILE_WIDTH_SCALE_FACTOR = 0.5
SNAKE_PROJECTILE_HEIGHT_SCALE_FACTOR = 0.5